services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    environment:
      - CLICKHOUSE_DB=photos
      - CLICKHOUSE_USER=app
      - CLICKHOUSE_PASSWORD=supersecret   # pick your own
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - ch_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d

    ports:
      - "8123:8123"      # HTTP
      # removed "9000:9000" to avoid conflict with MinIO
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-admin12345}
    volumes: [minio_data:/data]
    ports:
      - "9000:9000"      # S3 API
      - "9001:9001"      # Console
    restart: unless-stopped

  app:
    build: ./app
    env_file: ./.env
    depends_on: [clickhouse, minio]
    ports: ["8080:8080"]
    volumes:
      - /mnt/unraid/storage/Photos:/photos:ro
    restart: unless-stopped

  ingest:
    build: ./ingest
    env_file: ./.env
    depends_on: [clickhouse, minio]
    volumes:
      - /mnt/unraid/storage/Photos:/photos:ro
    restart: unless-stopped

  dagster:
    build: ./dagster
    env_file: ./.env
    depends_on: [clickhouse, app]
    ports: ["3000:3000"]
    volumes: ["./dagster:/opt/dagster"]
    restart: unless-stopped

volumes:
  ch_data: {}
  minio_data: {}
